# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - Rcpp
  - RcppXPtrUtils
  - microbenchmark
  - ggplot2

after_success:
  - Rscript -e 'covr::codecov()'

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang
  
jobs:
  include:
    - os: osx
      osx_image: xcode12 # updated Catalina 2
     - os: osx
      osx_image: xcode11.6 # updated Catalina 1 
    - os: osx
      osx_image: xcode11.5 # original Catalina
