---
title: "Return prior"
author: "Bob Verity and Pete Winskill"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Return prior}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
set.seed(1)
# load the drjacoby package
library(drjacoby)
```
**Purpose:** to check that *drjacoby* returns the prior distribution when no likelihood is used.

## Model

Four parameters, each representing a different one of the four possible parameter transformations internally. Each parameter is given a suitable informative prior over it's domain.

Parameters dataframe:

```{r}
df_params <- define_params(name = "real_line", min = -Inf, max = Inf,
                           name = "neg_line", min = -Inf, max = 0,
                           name = "pos_line", min = 0, max = Inf,
                           name = "unit_interval", min = 0, max = 1)
```

## Run MCMC

```{r}
mcmc <- dj$new(data = list(x = -1),
               df_params = df_params,
               loglike = loglike_null,
               logprior = logprior_return,
               chains = 10L)
mcmc$burn(iterations = 1000L, silent = TRUE)
mcmc$sample(iterations = 10000L, silent = TRUE)
```

## Plots

```{r, fig.width=6, fig.height=5}
output_sub <- mcmc$output(phase = "sample")

# Real line
hist(output_sub$real_line, breaks = 100, probability = TRUE,
     col = "black", main = "Real line", xlab = "")
x <- seq(-5, 5, l = 1001)
lines(x, dnorm(x), col = 2, lwd = 2)

# Negative line
hist(output_sub$neg_line, breaks = 100, probability = TRUE,
     col = "black", main = "Negative line", xlab = "")
x <- seq(-100, 0, l = 1001)
lines(x, dgamma(-x, shape = 5, scale = 5), col = 2, lwd = 2)

# Positive line
hist(output_sub$pos_line, breaks = 100, probability = TRUE,
     col = "black", main = "Positive line", xlab = "")
x <- seq(0, 100, l = 1001)
lines(x, dgamma(x, shape = 5, scale = 5), col = 2, lwd = 2)

# Unit interval
hist(output_sub$unit_interval, breaks = seq(0, 1, 0.01), probability = TRUE,
     col = "black", main = "Unit interval", xlab = "")
x <- seq(0, 10, l = 1001)
lines(x, dbeta(x, shape1 = 3, shape2 = 3), col = 2, lwd = 2)
```
