// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// foo_test
void foo_test();
RcppExport SEXP _drjacoby_foo_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    foo_test();
    return R_NilValue;
END_RCPP
}
// main_cpp
Rcpp::List main_cpp(Rcpp::List args);
RcppExport SEXP _drjacoby_main_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(main_cpp(args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_drjacoby_foo_test", (DL_FUNC) &_drjacoby_foo_test, 0},
    {"_drjacoby_main_cpp", (DL_FUNC) &_drjacoby_main_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_drjacoby(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
