# Generated by cpp11: do not edit by hand

mcmc <- function(chain, theta_init, theta_names, transform_type, theta_min, theta_max, blocks_list, n_unique_blocks, data, burnin, samples, ll_f, lp_f, target_acceptance, misc, n_rungs, beta_init, swap, infer_parameter, silent) {
  .Call(`_drjacoby_mcmc`, chain, theta_init, theta_names, transform_type, theta_min, theta_max, blocks_list, n_unique_blocks, data, burnin, samples, ll_f, lp_f, target_acceptance, misc, n_rungs, beta_init, swap, infer_parameter, silent)
}
