# Generated by cpp11: do not edit by hand

mcmc <- function(chain, burnin, iterations, iteration_counter_init, silent, theta_init, theta_names, transform_type, theta_min, theta_max, infer_parameter, data, ll_f, lp_f, misc, proposal_sd_init, acceptance_init, target_acceptance, swap, beta_init, swap_acceptance_init, blocks_list, n_unique_blocks) {
  .Call(`_drjacoby_mcmc`, chain, burnin, iterations, iteration_counter_init, silent, theta_init, theta_names, transform_type, theta_min, theta_max, infer_parameter, data, ll_f, lp_f, misc, proposal_sd_init, acceptance_init, target_acceptance, swap, beta_init, swap_acceptance_init, blocks_list, n_unique_blocks)
}
