# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_cpp <- function(args) {
    .Call(`_drjacoby_test_cpp`, args)
}

main_cpp <- function(args) {
    .Call(`_drjacoby_main_cpp`, args)
}

