# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dummy1_cpp <- function(args) {
    .Call(`_drjacoby_dummy1_cpp`, args)
}

